#ifndef PIPELINE_FFI_H
#define PIPELINE_FFI_H

// Auto-generated by cbindgen — do NOT edit by hand. Regenerate with: cbindgen --config cbindgen.toml --crate pipeline-ffi --output include/pipeline_ffi.h

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>

/**
 * Opaque owned UTF-8 string handed to C. Free with [`pipeline_string_free`].
 */
typedef struct PipelineString PipelineString;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Pointer to the UTF-8 bytes of a `PipelineString` (NUL-terminated).
 *
 * # Safety
 * `p` must be a pointer returned by this library and not yet freed.
 */
const char *pipeline_string_data(const PipelineString *p);

/**
 * Free a `PipelineString` returned by this library.
 *
 * # Safety
 * `p` must be a pointer returned by this library and not freed before.
 */
void pipeline_string_free(PipelineString *p);

/**
 * The library version string.
 */
PipelineString *pipeline_ffi_version(void);

/**
 * The platforms the engine supports, as a JSON array of keys
 * (`["argo","aws_codebuild",…]`). The single source of truth for the UI's
 * platform pickers — so they never drift from [`pipeline_forward::PLATFORMS`].
 */
PipelineString *pipeline_platforms(void);

/**
 * The platform's conventional pipeline file name (what a save dialog should
 * suggest), as JSON `{"name": "<file>"}`. Unknown platforms get the generic
 * `pipeline.yml`.
 *
 * # Safety
 * `kind` must be null or a valid C string.
 */
PipelineString *pipeline_default_file_name(const char *kind);

/**
 * Whether `kind`'s pipelines can be run locally in Docker, as JSON
 * `{"runnable": <bool>, "reason": "<why not>"}`. `reason` is empty when
 * runnable. Lets the UI disable the Run button for translate-only platforms
 * instead of offering a dead click.
 *
 * # Safety
 * `kind` must be null or a valid C string.
 */
PipelineString *pipeline_run_support(const char *kind);

/**
 * Best-effort platform detection from source text. Returns JSON
 * `{"kind": "<platform>"}` (a key from [`pipeline_forward::PLATFORMS`]), or
 * `{"kind": "unknown"}` if nothing matches.
 *
 * # Safety
 * `yaml` must be null or a valid C string.
 */
PipelineString *pipeline_detect_source_kind(const char *yaml);

/**
 * Detection that prefers the file NAME (`.gitlab-ci.yml`, `Jenkinsfile`, …)
 * over the content — the same logic the CLI uses. `path` may be empty to fall
 * back to pure content detection. Returns `{"kind": "<platform>|unknown"}`.
 *
 * # Safety
 * `path` and `yaml` must be null or valid C strings.
 */
PipelineString *pipeline_detect_with_path(const char *path, const char *yaml);

/**
 * Forward `yaml` for `kind` and return the SVG diagram (raw markup).
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_render_svg(const char *yaml,
                                    const char *kind,
                                    const char *_trigger,
                                    const char *_ref,
                                    int _show_scripts,
                                    int _show_capabilities,
                                    const char *_include_root);

/**
 * Forward `yaml` for `kind` and return `{svg, layout:{width,height,jobs}}`.
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_render_svg_with_layout(const char *yaml,
                                                const char *kind,
                                                const char *_trigger,
                                                const char *_ref,
                                                int _show_scripts,
                                                int _show_capabilities,
                                                const char *_include_root);

/**
 * Forward `yaml` for `kind` and return the runbook `{overview, toc, jobs,
 * skipped}` JSON.
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_render_html(const char *yaml,
                                     const char *kind,
                                     const char *_trigger,
                                     const char *_ref,
                                     const char *_include_root);

/**
 * Like [`pipeline_render_html`] but in `locale` (e.g. "en" / "de"). An empty
 * locale falls back to the default. The runbook prose is localized.
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_render_html_in(const char *yaml,
                                        const char *kind,
                                        const char *locale,
                                        const char *_trigger,
                                        const char *_ref,
                                        const char *_include_root);

/**
 * Forward `yaml` for `kind` and return `{pipeline:{name,jobs:[…]}}`.
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_inspect_json(const char *yaml,
                                      const char *kind,
                                      const char *_trigger,
                                      const char *_ref,
                                      const char *_include_root);

/**
 * Apply a value edit and return `{"ok":true,"yaml":"<new source>"}` (or
 * `{"error":…}`). `hub` is the 64-char `GhostId` hex from a diagram line's
 * `data-hub`; the field is changed *on the Hub-IR* and the source is
 * regenerated through the backward TGG cascade (the IR is canonical, so the
 * output normalises — formatting/key-order, not a byte patch).
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_edit_field(const char *yaml,
                                    const char *kind,
                                    const char *hub,
                                    const char *new_value);

/**
 * Duplicate the construct at `hub` (a job or step): clone it in place via the
 * Hub-IR and re-emit. Returns `{"ok":true,"yaml":…}` | `{"error":…}`.
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_duplicate(const char *yaml, const char *kind, const char *hub);

/**
 * Delete the construct at `hub` (a job or step) from the Hub-IR and re-emit.
 * Returns `{"ok":true,"yaml":…}` | `{"error":…}`.
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_delete(const char *yaml, const char *kind, const char *hub);

/**
 * Export the human-readable runbook in `format` ("md" | "html" | "doc"). On
 * success returns `{"ok":true,"content":"…","ext":"md|html|rtf"}`; otherwise
 * `{"error":…}`. The IR is canonical, so every format is a clean projection.
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_export_runbook(const char *yaml, const char *kind, const char *format);

/**
 * Like [`pipeline_export_runbook`] but in `locale` (e.g. "en" / "de"). An empty
 * locale falls back to the default.
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_export_runbook_in(const char *yaml,
                                           const char *kind,
                                           const char *format,
                                           const char *locale);

/**
 * Capability profile of a pipeline, derived from the Hub-IR via the shared
 * [`pipeline_render::capabilities_json`]. Returns
 * `{overall, summary, jobs, steps, features}` | `{error}`.
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_capabilities_json(const char *yaml,
                                           const char *kind,
                                           const char *_include_root);

/**
 * Migrate `yaml` from platform `kind` to `target`: forward to the Hub-IR,
 * re-key to the target vocabulary, re-emit. Returns `{"ok":true,"yaml":…}` |
 * `{"error":…}`. Fidelity is best between structurally compatible platforms.
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_migrate(const char *yaml,
                                 const char *kind,
                                 const char *target,
                                 const char *_include_root);

/**
 * Compose the recipe files at `paths` into a pipeline rendered to `target`.
 * Returns `{"ok":true,"yaml":…}` | `{"error":…}`.
 *
 * # Safety
 * `paths` must point to `count` valid C strings; `target` null or valid.
 */
PipelineString *pipeline_compose_recipes(const char *const *paths,
                                         uintptr_t count,
                                         const char *target);

/**
 * List recipes for the browser: standard library + configured user sources,
 * filtered by `query` (id/description/tags substring) and ordered by `sort`
 * ("name" | "tag" | "source"). Returns
 * `{"ok":true,"recipes":[…],"warnings":[…]}`.
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_list_recipes(const char *query,
                                      const char *sort,
                                      const char *config_path,
                                      const char *cache_dir);

/**
 * A generated, localized structural description (Markdown) of a recipe, via the
 * prose doc mechanism. `locale` is e.g. "en" / "de". Returns
 * `{"ok":true,"markdown":…}` | `{"error":…}`.
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_describe_recipe(const char *recipe_id,
                                         const char *locale,
                                         const char *config_path,
                                         const char *cache_dir);

/**
 * Apply the recipe `recipe_id` to the current pipeline `yaml` of platform
 * `kind`: the recipe's jobs are merged in and the result re-emitted in the same
 * platform — the graph-edit "apply recipe" operation. An empty `yaml` starts a
 * fresh pipeline. Returns `{"ok":true,"yaml":…}` | `{"error":…}`.
 *
 * # Safety
 * All pointers must be null or valid C strings.
 */
PipelineString *pipeline_apply_recipe(const char *yaml,
                                      const char *kind,
                                      const char *recipe_id,
                                      const char *config_path,
                                      const char *cache_dir);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PIPELINE_FFI_H */
