#![allow(
    clippy::doc_markdown,
    reason = "module docs reference type names like TypedGraph in prose"
)]

//! Catalog-driven CST → seesaw `TypedGraph` seeder.
//!
//! Shared primitives across every YAML platform's TGG bridge:
//! recursive walk, construct-tagging from a per-platform
//! classification table, carrier-comment promotion, scalar
//! resolution, anchor/merge resolution.
//!
//! What's *not* here: the top-level dispatch — i.e. how to walk
//! the root mapping and decide which entries are jobs vs meta vs
//! pipeline-level. That's platform-specific and lives in each
//! per-platform crate's `seed.rs`, calling into the primitives
//! below.

use std::collections::BTreeMap;

pub mod classify;
pub mod emit;
pub mod emit_earthfile;
pub mod emit_jenkinsfile;
pub mod platforms;
pub mod scalar;

pub use pipeline_cst::AnchorTable;
use pipeline_cst::{mapping_entries_logical, Document, EntrySource, Node, NodeKind};
use seesaw_core::graph::{GhostId, Status, TypedGraph};

// ─── CST type identifiers ─────────────────────────────────────────
pub const CST_DOCUMENT: &str = "cst:Document";
pub const CST_MAPPING: &str = "cst:Mapping";
pub const CST_MAPPING_ENTRY: &str = "cst:MappingEntry";
pub const CST_SEQUENCE: &str = "cst:Sequence";
pub const CST_SEQUENCE_ITEM: &str = "cst:SequenceItem";
pub const CST_SCALAR: &str = "cst:Scalar";
/// Carrier annotation `# @hub:<C>.<F>=<v>` promoted from a CST
/// Comment by the seeder — load-bearing IR-side data the platform
/// schema has no native field for.
pub const CST_CARRIER_COMMENT: &str = "cst:CarrierComment";
/// A non-carrier source comment (`# foo`). Lifted into the graph so
/// the cascade can carry it through to Hub-IR as `hub:comment` and
/// back to a CST comment on emit. Distinct from `cst:CarrierComment`
/// because the comment text has no structured `@hub:` meaning — it
/// is verbatim user content the emitter must preserve.
pub const CST_USER_COMMENT: &str = "cst:UserComment";

// ─── CST edge identifiers ─────────────────────────────────────────
pub const CST_HAS_CHILD: &str = "cst:has_child";
pub const CST_VALUE_OF: &str = "cst:value_of";

/// Standard attribute names on CST nodes.
pub mod cst_attr {
    pub const SPAN_START: &str = "span_start";
    pub const SPAN_END: &str = "span_end";
    pub const KEY: &str = "key";
    pub const TEXT: &str = "text";
    pub const PARENT_KEY: &str = "parent_key";
    pub const CONSTRUCT: &str = "construct";
    pub const CONSTRUCT_NAME: &str = "construct_name";
    pub const SOURCE_FILE: &str = "source_file";
    pub const FROM_MERGE: &str = "from_merge";
    pub const MERGED_FROM_ANCHOR: &str = "merged_from_anchor";
    pub const ANCHOR: &str = "anchor";
    pub const TARGET_CONSTRUCT: &str = "target_construct";
    /// Last segment of `target_path` — used as `hub:attr.name` in
    /// the binding side of carrier rules. For a flat carrier
    /// (`@hub:C.f=v`) `target_field == target_path`; for a ref-field
    /// carrier (`@hub:C.f.l=v`) `target_path == "f.l"` while
    /// `target_field == "l"`.
    pub const TARGET_FIELD: &str = "target_field";
    /// Full dot-separated carrier path — the literal matched in the
    /// rule's L pattern. Distinguishes flat from ref-field carriers
    /// without needing a separate node kind.
    pub const TARGET_PATH: &str = "target_path";
    pub const VALUE: &str = "value";
}

/// Per-platform classification table mapping a mapping-entry key
/// to the IR construct kind its value mapping represents.
/// Generated by `catalog/gen_classification.py` from `ir.toml`.
pub type Classify<'a> = &'a [(&'a str, &'a str)];

/// Lookup helper for classification tables — O(n) but `n` is small
/// (max 35 entries) and tables are static, so cheaper than a
/// HashMap setup.
///
/// A `map<construct>` field is encoded in the table as `"map:<construct>"`
/// (e.g. github `services` → `"map:service"`): the entry's value is a MAP
/// whose entries' values are the constructs, NOT a single construct. This
/// lookup strips that marker so every caller sees the clean construct kind;
/// [`is_map_construct`] reports the marker for the seeder's one-level recurse.
#[must_use]
pub fn lookup_classify<'a>(table: Classify<'a>, key: &str) -> Option<&'a str> {
    table
        .iter()
        .find(|(k, _)| *k == key)
        .map(|(_, v)| v.strip_prefix("map:").unwrap_or(v))
}

/// Whether `key` classifies to a `map<construct>` field — the value is a
/// map of named construct instances (`services: {main: {...}}`), so the
/// seeder must tag each INNER entry's value-mapping, not the outer map.
#[must_use]
pub fn is_map_construct(table: Classify<'_>, key: &str) -> bool {
    table
        .iter()
        .find(|(k, _)| *k == key)
        .is_some_and(|(_, v)| v.starts_with("map:"))
}

/// The seeded graph + the document node's id, returned by every
/// platform's `seed_from_document`.
pub struct SeededGraph {
    pub graph: TypedGraph,
    pub doc_id: GhostId,
}

/// Build a `BTreeMap<String, String>` from `&[(name, value)]` pairs.
#[must_use]
pub fn make_attrs(pairs: &[(&str, &str)]) -> BTreeMap<String, String> {
    pairs
        .iter()
        .map(|(k, v)| ((*k).to_string(), (*v).to_string()))
        .collect()
}

/// Add a child node + a Solid edge from parent to it. Returns the
/// new node's id.
pub fn add_child(
    graph: &mut TypedGraph,
    parent: GhostId,
    edge_kind: &str,
    type_id: &str,
    attrs: BTreeMap<String, String>,
) -> GhostId {
    let child = graph.add_solid_child_node(parent, edge_kind, type_id, attrs);
    graph.add_edge(parent, child, edge_kind, BTreeMap::new(), Status::Solid);
    child
}

/// Create a fresh graph with a `cst:Document` baseline node.
/// Returns `(graph, doc_id)`.
#[must_use]
pub fn make_document(source_file: &str, source: &str) -> (TypedGraph, GhostId) {
    let mut graph = TypedGraph::new();
    let source_len = source.len().to_string();
    let doc_attrs = make_attrs(&[
        (cst_attr::SOURCE_FILE, source_file),
        (cst_attr::SPAN_START, "0"),
        (cst_attr::SPAN_END, &source_len),
    ]);
    let doc_id = graph.add_baseline_node(CST_DOCUMENT, source_file, doc_attrs);
    (graph, doc_id)
}

// ─── Carrier-comment parsing + promotion ──────────────────────────

/// Parsed pieces of a carrier sigil:
/// - `construct`: the IR construct id (the part after `@hub:`, before
///   the first `.`).
/// - `path`: the full dot-separated field path (e.g. `"environment.name"`
///   for a ref-field carrier, `"name"` for a flat one).
/// - `value`: the right-hand side with outer quotes stripped.
pub struct ParsedCarrier<'a> {
    pub construct: &'a str,
    pub path: &'a str,
    pub value: String,
}

impl ParsedCarrier<'_> {
    /// The last segment of `path` — what binds to `hub:attr.name`.
    #[must_use]
    pub fn leaf(&self) -> &str {
        self.path
            .rsplit_once('.')
            .map_or(self.path, |(_, last)| last)
    }
}

/// Parse a CST comment's raw text as a carrier sigil.
/// `# @hub:<construct>.<path>=<value>` where `path` is a dot-separated
/// sequence of one or more field names. A single-segment path is a
/// flat carrier; a two-segment path is a ref-field carrier (the first
/// segment is the parent construct's ref field, the second the leaf
/// scalar on the referenced sub-construct). Whitespace-tolerant; outer
/// `"`/`'` wrapping the value is stripped. Returns `None` for a
/// non-carrier comment.
#[must_use]
pub fn parse_carrier(text: &str) -> Option<ParsedCarrier<'_>> {
    let body = text.strip_prefix('#')?.trim();
    let body = body.strip_prefix("@hub:")?;
    let (path, value) = body.split_once('=')?;
    let (construct, rest) = path.split_once('.')?;
    let value = value.trim();
    let value = value
        .strip_prefix('"')
        .and_then(|v| v.strip_suffix('"'))
        .or_else(|| value.strip_prefix('\'').and_then(|v| v.strip_suffix('\'')))
        .unwrap_or(value);
    Some(ParsedCarrier {
        construct: construct.trim(),
        path: rest.trim(),
        value: value.to_string(),
    })
}

/// Promote every `# @hub:<C>.<path>=<v>` comment among a container's
/// AST children to a `cst:CarrierComment` graph node, attached to
/// `container_id` via `cst:has_child`. Non-carrier comments are
/// left in the AST but not promoted.
pub fn seed_carrier_comments(
    graph: &mut TypedGraph,
    container_id: GhostId,
    container_node: &Node,
    source: &str,
) {
    for child in &container_node.children {
        if !matches!(child.kind, NodeKind::Comment { .. }) {
            continue;
        }
        let text = &source[child.span.start..child.span.end];
        let span_start = child.span.start.to_string();
        let span_end = child.span.end.to_string();
        if let Some(parsed) = parse_carrier(text) {
            let leaf = parsed.leaf();
            let attrs = make_attrs(&[
                (cst_attr::TARGET_CONSTRUCT, parsed.construct),
                (cst_attr::TARGET_PATH, parsed.path),
                (cst_attr::TARGET_FIELD, leaf),
                (cst_attr::VALUE, &parsed.value),
                (cst_attr::SPAN_START, &span_start),
                (cst_attr::SPAN_END, &span_end),
            ]);
            add_child(
                graph,
                container_id,
                CST_HAS_CHILD,
                CST_CARRIER_COMMENT,
                attrs,
            );
        } else {
            // Non-carrier source comment — preserve verbatim text so
            // the reverse cascade can re-emit it. Strip the leading
            // `#` + one optional space, store the remainder as `text`.
            let body = text
                .strip_prefix('#')
                .map_or(text, |s| s.strip_prefix(' ').unwrap_or(s))
                .trim_end();
            let attrs = make_attrs(&[
                (cst_attr::TEXT, body),
                (cst_attr::SPAN_START, &span_start),
                (cst_attr::SPAN_END, &span_end),
            ]);
            add_child(graph, container_id, CST_HAS_CHILD, CST_USER_COMMENT, attrs);
        }
    }
}

/// Synthesise a `cst:CarrierComment[target_path=name]` child for
/// a construct mapping's natural identity (job key, sub-construct
/// key). Same path as a source-level `# @hub:<C>.name=...` — model
/// (a) uniform satellite where `name` is a hub:attr child.
pub fn synthesize_name_carrier(
    graph: &mut TypedGraph,
    container_id: GhostId,
    construct: &str,
    name: &str,
    span_start: usize,
    span_end: usize,
) {
    let s_start = span_start.to_string();
    let s_end = span_end.to_string();
    let attrs = make_attrs(&[
        (cst_attr::TARGET_CONSTRUCT, construct),
        (cst_attr::TARGET_PATH, "name"),
        (cst_attr::TARGET_FIELD, "name"),
        (cst_attr::VALUE, name),
        (cst_attr::SPAN_START, &s_start),
        (cst_attr::SPAN_END, &s_end),
    ]);
    add_child(
        graph,
        container_id,
        CST_HAS_CHILD,
        CST_CARRIER_COMMENT,
        attrs,
    );
}

// ─── Recursive CST → graph walker ─────────────────────────────────

/// Walk into a mapping-entry's value, adding it to the graph as a
/// child of `entry_id` via `cst:value_of`. Resolves anchors,
/// propagates `parent_key`, and — if the entry's key matches a
/// classify-table entry — tags the value mapping with
/// `construct=<kind>` and synthesises a name carrier so the value
/// flows through the normal carrier path.
#[allow(
    clippy::too_many_arguments,
    reason = "all arguments are load-bearing context for the recursive walk; bundling into a struct would just rename them"
)]
pub fn seed_value(
    graph: &mut TypedGraph,
    entry_id: GhostId,
    entry_key: &str,
    entry_anchor: Option<&str>,
    value: &Node,
    source: &str,
    anchors: &AnchorTable<'_>,
    classify: Classify<'_>,
) -> GhostId {
    // `{}` is an empty flow MAPPING, but the CST parser renders it as a
    // Scalar "{}". When it is a field VALUE (this entry has a key), normalise
    // it to an empty cst:Mapping so block-typed fields (e.g. buildkite
    // `waiter: {}`) capture their presence/identity via block_attr instead of
    // dropping to a bare scalar that no rule matches. Sequence items (`- {}`)
    // are seeded via seed_node directly and are NOT normalised — they have no
    // key, so an empty construct item would only inflate indistinguishable
    // empty-construct counts (roundtrip multiplicity).
    let is_empty_flow_map = matches!(value.kind, NodeKind::Scalar { .. })
        && matches!(
            scalar::resolve(source, value.span.start, value.span.end)
                .unwrap_or_default()
                .trim(),
            "{}" | "{ }"
        );
    let value_id = if is_empty_flow_map {
        let attrs = make_attrs(&[
            (cst_attr::SPAN_START, &value.span.start.to_string()),
            (cst_attr::SPAN_END, &value.span.end.to_string()),
        ]);
        add_child(graph, entry_id, CST_VALUE_OF, CST_MAPPING, attrs)
    } else {
        seed_node(
            graph,
            entry_id,
            CST_VALUE_OF,
            value,
            entry_key,
            source,
            anchors,
            classify,
        )
    };
    graph.set_node_attr(&value_id, cst_attr::PARENT_KEY, entry_key);
    if graph
        .get_node(&value_id)
        .is_some_and(|n| n.type_id == CST_MAPPING)
    {
        if let Some(kind) = lookup_classify(classify, entry_key) {
            if is_map_construct(classify, entry_key) {
                // map<construct> (`services: {main: {...}}`): the value is a
                // MAP of named instances, so tag each INNER entry's value —
                // never the outer map wrapper. Same one-level-deep mechanism
                // as a nested jobs block. (The generic single-construct path
                // below would tag the wrapper as construct=service with
                // name=<field key>, dropping the real entries — the github
                // job.services loss.)
                tag_map_entries_as_construct(graph, value_id, kind);
            } else {
                graph.set_node_attr(&value_id, cst_attr::CONSTRUCT, kind);
                // Only synthesise a name-carrier when the entry's key
                // names the construct itself (top-level `build:` is a
                // job name, top-level `pipeline:` is a pipeline name).
                // For field-keyed entries (`artifacts:` under a job,
                // `image:` under a step, `cache:` etc.) the key is the
                // IR FIELD name, not the sub-construct's name — adding
                // a fake `name = <key>` carrier would override the real
                // `name:` value that lives inside the sub-mapping.
                if kind == "job" || kind == "pipeline" {
                    synthesize_name_carrier(
                        graph,
                        value_id,
                        kind,
                        entry_key,
                        value.span.start,
                        value.span.end,
                    );
                }
            }
        }
    }
    let resolved_anchor = value.anchor.as_deref().or(entry_anchor);
    if let Some(name) = resolved_anchor {
        graph.set_node_attr(&value_id, cst_attr::ANCHOR, name);
    }
    value_id
}

/// Add a CST node to the graph as a child of `parent` via
/// `edge_kind` and recurse into its children. Returns the new
/// node's id. `parent_key` is the surrounding mapping-entry key,
/// propagated so that scalars in sequences inherit their list's
/// key as `parent_key`.
#[allow(
    clippy::too_many_arguments,
    reason = "all arguments are load-bearing context for the recursive walk; bundling into a struct would just rename them"
)]
/// Seed one element of a construct list: create a `cst:SequenceItem` slot on
/// `coll_id`, seed `inner` as its value, and — when the list classifies to an
/// IR construct (`item_construct`) and the value is a mapping — tag it
/// `construct=<kind>` and synthesise a name carrier from its `name:` entry.
/// Shared by the flat and the nested-list-flattening paths in [`seed_node`].
#[allow(clippy::too_many_arguments)]
fn seed_construct_item(
    graph: &mut TypedGraph,
    coll_id: GhostId,
    inner: &Node,
    index: usize,
    item_construct: Option<&str>,
    parent_key: &str,
    source: &str,
    anchors: &AnchorTable<'_>,
    classify: Classify<'_>,
) {
    let item_attrs = make_attrs(&[
        ("index", &index.to_string()),
        (cst_attr::SPAN_START, &inner.span.start.to_string()),
        (cst_attr::SPAN_END, &inner.span.end.to_string()),
    ]);
    let item_id = add_child(graph, coll_id, CST_HAS_CHILD, CST_SEQUENCE_ITEM, item_attrs);
    let inner_id = seed_node(
        graph,
        item_id,
        CST_VALUE_OF,
        inner,
        parent_key,
        source,
        anchors,
        classify,
    );
    if let Some(kind) = item_construct {
        if graph
            .get_node(&inner_id)
            .is_some_and(|n| n.type_id == CST_MAPPING)
        {
            graph.set_node_attr(&inner_id, cst_attr::CONSTRUCT, kind);
            // Best-effort name carrier from a `name:` entry on the item, if
            // any — mirrors how seed_value handles the mapping-keyed-by-name
            // pattern.
            let name_attr = inner.children.iter().find_map(|e| {
                if let NodeKind::MappingEntry { key_text } = &e.kind {
                    if key_text == "name" {
                        return e.children.get(1).and_then(|v| {
                            if let NodeKind::Scalar { .. } = v.kind {
                                Some(&source[v.span.start..v.span.end])
                            } else {
                                None
                            }
                        });
                    }
                }
                None
            });
            if let Some(name) = name_attr {
                let trimmed = name.trim();
                let trimmed = trimmed
                    .strip_prefix('"')
                    .and_then(|s| s.strip_suffix('"'))
                    .or_else(|| {
                        trimmed
                            .strip_prefix('\'')
                            .and_then(|s| s.strip_suffix('\''))
                    })
                    .unwrap_or(trimmed);
                synthesize_name_carrier(
                    graph,
                    inner_id,
                    kind,
                    trimmed,
                    inner.span.start,
                    inner.span.end,
                );
            }
        }
    }
}

#[allow(
    clippy::too_many_arguments,
    clippy::too_many_lines,
    reason = "the recursive CST walk threads load-bearing context; bundling renames it"
)]
pub fn seed_node(
    graph: &mut TypedGraph,
    parent: GhostId,
    edge_kind: &str,
    node: &Node,
    parent_key: &str,
    source: &str,
    anchors: &AnchorTable<'_>,
    classify: Classify<'_>,
) -> GhostId {
    match &node.kind {
        NodeKind::Mapping => {
            let attrs = make_attrs(&[
                (cst_attr::SPAN_START, &node.span.start.to_string()),
                (cst_attr::SPAN_END, &node.span.end.to_string()),
            ]);
            let id = add_child(graph, parent, edge_kind, CST_MAPPING, attrs);
            seed_carrier_comments(graph, id, node, source);
            // Merge-aware logical view so `<<:` resolves; merged
            // entries point at their anchor body's value-node.
            for logical in mapping_entries_logical(node, anchors) {
                let (span_start, span_end) = (logical.value.span.start, logical.value.span.end);
                let (from_merge_str, anchor_name) = match &logical.source {
                    EntrySource::Direct => ("false", None),
                    EntrySource::Merged { anchor } => ("true", Some(anchor.as_str())),
                };
                let span_start_s = span_start.to_string();
                let span_end_s = span_end.to_string();
                let mut pairs: Vec<(&str, &str)> = vec![
                    (cst_attr::KEY, logical.key.as_str()),
                    ("entry_role", "annotation"),
                    (cst_attr::FROM_MERGE, from_merge_str),
                    (cst_attr::SPAN_START, &span_start_s),
                    (cst_attr::SPAN_END, &span_end_s),
                ];
                if let Some(name) = anchor_name {
                    pairs.push((cst_attr::MERGED_FROM_ANCHOR, name));
                }
                let entry_attrs = make_attrs(&pairs);
                let entry_id = add_child(graph, id, CST_HAS_CHILD, CST_MAPPING_ENTRY, entry_attrs);
                seed_value(
                    graph,
                    entry_id,
                    logical.key.as_str(),
                    None,
                    logical.value,
                    source,
                    anchors,
                    classify,
                );
            }
            id
        }
        NodeKind::Sequence => {
            let attrs = make_attrs(&[
                (cst_attr::SPAN_START, &node.span.start.to_string()),
                (cst_attr::SPAN_END, &node.span.end.to_string()),
            ]);
            let id = add_child(graph, parent, edge_kind, CST_SEQUENCE, attrs);
            // If the sequence's parent_key classifies to an IR
            // construct (e.g. `steps`, `tasks`, `jobs`, `actions`),
            // every mapping item in the sequence is an instance of
            // that construct. Tag it so the construct/field rules
            // anchor on it. Without this, list-of-objects platforms
            // (buildkite, drone, tekton, woodpecker, azure jobs,
            // aws_codepipeline actions, google_cloudbuild steps,
            // …) leave job/step mappings untagged and the forward
            // cascade can only see the pipeline-level shell.
            let item_construct = lookup_classify(classify, parent_key);
            let mut slot = 0usize;
            for child in &node.children {
                if let NodeKind::SequenceItem = &child.kind {
                    let Some(inner) = child.children.first() else {
                        continue;
                    };
                    // NESTED `list<list<construct>>` (argo `steps:
                    // list<list<workflow_step>>` — parallel groups of
                    // sequential steps): FLATTEN one level so each inner-list
                    // mapping is a direct construct item of THIS collection.
                    // The hub models a ref-list field as a FLAT collection (no
                    // grouping concept), and the TGG engine forbids a rule
                    // referencing its own freshly-created inner collection, so
                    // structural nesting cannot round-trip — the flat form is
                    // the faithful flat-hub representation, symmetric on emit.
                    if item_construct.is_some() && matches!(inner.kind, NodeKind::Sequence) {
                        for leaf_item in &inner.children {
                            if let NodeKind::SequenceItem = &leaf_item.kind {
                                if let Some(leaf) = leaf_item.children.first() {
                                    seed_construct_item(
                                        graph,
                                        id,
                                        leaf,
                                        slot,
                                        item_construct,
                                        parent_key,
                                        source,
                                        anchors,
                                        classify,
                                    );
                                    slot += 1;
                                }
                            }
                        }
                        continue;
                    }
                    seed_construct_item(
                        graph,
                        id,
                        inner,
                        slot,
                        item_construct,
                        parent_key,
                        source,
                        anchors,
                        classify,
                    );
                    slot += 1;
                }
            }
            id
        }
        // Every leaf collapses to a `cst:Scalar` carrying the
        // resolved logical text. Aliases, comments (non-carrier),
        // Document, MappingEntry and SequenceItem can't appear in a
        // value position — defensive fallthrough only.
        NodeKind::Scalar { .. }
        | NodeKind::Alias { .. }
        | NodeKind::Comment { .. }
        | NodeKind::Document
        | NodeKind::MappingEntry { .. }
        | NodeKind::SequenceItem => {
            let span_start = node.span.start.to_string();
            let span_end = node.span.end.to_string();
            let mut pairs: Vec<(&str, &str)> = vec![
                (cst_attr::SPAN_START, &span_start),
                (cst_attr::SPAN_END, &span_end),
            ];
            let text = scalar::resolve(source, node.span.start, node.span.end);
            if let Some(t) = &text {
                pairs.push((cst_attr::TEXT, t));
            }
            if !parent_key.is_empty() {
                pairs.push((cst_attr::PARENT_KEY, parent_key));
            }
            add_child(graph, parent, edge_kind, CST_SCALAR, make_attrs(&pairs))
        }
    }
}

/// Mark a top-level entry as a job-bearing structural placeholder
/// and seed its value through the regular path. Idiomatic for
/// platforms whose jobs are unnamed top-level entries (GitLab-
/// style): non-meta entries get `entry_role=job` and the value-
/// mapping (if any) is tagged `construct=job` with a synthesised
/// name carrier from the entry key.
#[allow(clippy::too_many_arguments)]
pub fn seed_top_entry_as_job(
    graph: &mut TypedGraph,
    parent_map: GhostId,
    entry_node: &Node,
    key: &str,
    value: &Node,
    source: &str,
    anchors: &AnchorTable<'_>,
    classify: Classify<'_>,
) {
    let attrs = make_attrs(&[
        (cst_attr::KEY, key),
        ("entry_role", "job"),
        (cst_attr::FROM_MERGE, "false"),
        (cst_attr::SPAN_START, &entry_node.span.start.to_string()),
        (cst_attr::SPAN_END, &entry_node.span.end.to_string()),
    ]);
    let entry_id = add_child(graph, parent_map, CST_HAS_CHILD, CST_MAPPING_ENTRY, attrs);
    let value_id = seed_value(
        graph,
        entry_id,
        key,
        entry_node.anchor.as_deref(),
        value,
        source,
        anchors,
        classify,
    );
    if graph
        .get_node(&value_id)
        .is_some_and(|n| n.type_id == CST_MAPPING)
    {
        graph.set_node_attr(&value_id, cst_attr::CONSTRUCT, "job");
        // rc8 first-class re-architecture: lift the parent entry key onto the
        // job mapping as a first-class `name` attribute. The construct rule
        // propagates it to hub:job.name (no name satellite); emit derives the
        // `<name>:` containment nesting from has_job + hub:job.name.
        graph.set_node_attr(&value_id, "name", key);
        synthesize_name_carrier(
            graph,
            value_id,
            "job",
            key,
            entry_node.span.start,
            entry_node.span.end,
        );
    }
}

/// Mark a top-level entry as a job-bearing BLOCK: its value is a
/// mapping whose every child entry is a job (GitHub Actions
/// `jobs:`, CircleCI `jobs:`, Tekton `spec.tasks`, …). The entry
/// itself becomes `meta:<key>`; each child of the value-mapping
/// gets its value-mapping tagged `construct=job` with a
/// synthesised name carrier.
///
/// Returns the value-mapping's graph id so callers can do further
/// work on it. `None` if the value isn't a mapping (malformed).
#[allow(clippy::too_many_arguments)]
pub fn seed_top_entry_as_job_block(
    graph: &mut TypedGraph,
    parent_map: GhostId,
    entry_node: &Node,
    key: &str,
    value: &Node,
    source: &str,
    anchors: &AnchorTable<'_>,
    classify: Classify<'_>,
) -> Option<GhostId> {
    let role = format!("meta:{key}");
    let attrs = make_attrs(&[
        (cst_attr::KEY, key),
        ("entry_role", &role),
        (cst_attr::FROM_MERGE, "false"),
        (cst_attr::SPAN_START, &entry_node.span.start.to_string()),
        (cst_attr::SPAN_END, &entry_node.span.end.to_string()),
    ]);
    let entry_id = add_child(graph, parent_map, CST_HAS_CHILD, CST_MAPPING_ENTRY, attrs);
    let value_id = seed_value(
        graph,
        entry_id,
        key,
        entry_node.anchor.as_deref(),
        value,
        source,
        anchors,
        classify,
    );
    if graph
        .get_node(&value_id)
        .is_none_or(|n| n.type_id != CST_MAPPING)
    {
        return None;
    }
    // `seed_value` consults the classify table on the entry key. For
    // job-bearing block entries (`jobs`, `steps` when it's a mapping,
    // …) that key often classifies to "job" itself — so the outer
    // container mapping ends up tagged construct=job by mistake (it's
    // not a job, it's a container of jobs). The child entries are
    // the actual jobs and get tagged by `tag_block_entries_as_job`
    // below. Strip the spurious outer tag here so only one hub:job
    // per child gets materialised.
    if let Some(node) = graph.get_node(&value_id) {
        if node.attrs.contains_key(cst_attr::CONSTRUCT) {
            // Remove via overwrite with empty — set_node_attr only
            // inserts; the engine doesn't expose a deleter at this
            // level. An empty construct value is filtered out by the
            // construct-rule's literal constraint.
            graph.set_node_attr(&value_id, cst_attr::CONSTRUCT, "");
        }
    }
    tag_block_entries_as_job(graph, value_id);
    Some(value_id)
}

/// Mark a top-level entry as platform meta-data (no IR semantics
/// at this level) and seed its value generically.
#[allow(clippy::too_many_arguments)]
pub fn seed_top_entry_as_meta(
    graph: &mut TypedGraph,
    parent_map: GhostId,
    entry_node: &Node,
    key: &str,
    value: &Node,
    source: &str,
    anchors: &AnchorTable<'_>,
    classify: Classify<'_>,
) {
    let role = format!("meta:{key}");
    let attrs = make_attrs(&[
        (cst_attr::KEY, key),
        ("entry_role", &role),
        (cst_attr::FROM_MERGE, "false"),
        (cst_attr::SPAN_START, &entry_node.span.start.to_string()),
        (cst_attr::SPAN_END, &entry_node.span.end.to_string()),
    ]);
    let entry_id = add_child(graph, parent_map, CST_HAS_CHILD, CST_MAPPING_ENTRY, attrs);
    seed_value(
        graph,
        entry_id,
        key,
        entry_node.anchor.as_deref(),
        value,
        source,
        anchors,
        classify,
    );
}

/// Iterate the children of a job-bearing block (e.g. GitHub's
/// `jobs:`) and tag each entry's value-mapping as `construct=job`
/// with a synthesised name carrier. Used when the platform nests
/// its jobs one level deep under a known key.
pub fn tag_block_entries_as_job(graph: &mut TypedGraph, block_value_id: GhostId) {
    tag_map_entries_as_construct(graph, block_value_id, "job");
}

/// Iterate a `map<construct>` block (`services: {main: {...}}`) and tag each
/// entry's value-mapping as `construct=<construct>`, synthesising a name
/// carrier from the entry key (the map key IS the instance's identity).
/// Generalises [`tag_block_entries_as_job`]: a `map<X>` field nests its X
/// instances one level deep, so the construct tag belongs on the INNER
/// value, never on the outer map wrapper (which has no construct).
pub fn tag_map_entries_as_construct(
    graph: &mut TypedGraph,
    block_value_id: GhostId,
    construct: &str,
) {
    let entries: Vec<(GhostId, String, usize, usize)> = graph
        .iter_edges()
        .into_iter()
        .filter(|(s, _, e)| *s == block_value_id && e.type_id == CST_HAS_CHILD)
        .filter_map(|(_, t, _)| {
            let node = graph.get_node(&t)?;
            if node.type_id != CST_MAPPING_ENTRY {
                return None;
            }
            let key = node.attrs.get(cst_attr::KEY)?.clone();
            let s_start = node.attrs.get(cst_attr::SPAN_START)?.parse().ok()?;
            let s_end = node.attrs.get(cst_attr::SPAN_END)?.parse().ok()?;
            Some((t, key, s_start, s_end))
        })
        .collect();

    for (entry_id, key, s_start, s_end) in entries {
        let value_id_opt = graph
            .iter_edges()
            .into_iter()
            .find(|(s, _, e)| *s == entry_id && e.type_id == CST_VALUE_OF)
            .map(|(_, t, _)| t);
        let Some(value_id) = value_id_opt else {
            continue;
        };
        if graph
            .get_node(&value_id)
            .is_none_or(|n| n.type_id != CST_MAPPING)
        {
            continue;
        }
        graph.set_node_attr(&value_id, cst_attr::CONSTRUCT, construct);
        synthesize_name_carrier(graph, value_id, construct, &key, s_start, s_end);
    }
}

/// Initial setup shared by every platform: create the cst:Document
/// node, find the root mapping, tag it `construct=pipeline`,
/// promote top-level carrier comments, and collect anchors.
/// Returns the parts every platform-specific dispatcher needs to
/// iterate root entries.
#[must_use]
pub fn open_pipeline<'doc>(doc: &'doc Document, source_file: &str) -> Option<PipelineSeed<'doc>> {
    let source = doc.source();
    let (mut graph, doc_id) = make_document(source_file, source);

    // A config file ALWAYS denotes exactly one pipeline — even an empty
    // one. The chaos walker can legitimately emit `{}` (an all-optional
    // root where every coin-flip came up false); our CST parser renders
    // `{}` as a Scalar, not a Mapping, so no Mapping child is found. Fall
    // back to the document root itself as the entry-iteration surrogate:
    // it carries no MappingEntry children, so zero entries are seeded, but
    // the empty pipeline mapping below is still created and round-trips
    // losslessly (empty pipeline -> `{}` -> empty pipeline).
    let top_mapping = doc
        .root()
        .children
        .iter()
        .find(|c| matches!(c.kind, NodeKind::Mapping))
        .unwrap_or_else(|| doc.root());

    let anchors = AnchorTable::collect(doc);
    let map_attrs = make_attrs(&[
        (cst_attr::SPAN_START, &top_mapping.span.start.to_string()),
        (cst_attr::SPAN_END, &top_mapping.span.end.to_string()),
    ]);
    let map_id = add_child(&mut graph, doc_id, CST_HAS_CHILD, CST_MAPPING, map_attrs);
    graph.set_node_attr(&map_id, cst_attr::CONSTRUCT, "pipeline");
    seed_carrier_comments(&mut graph, map_id, top_mapping, source);
    seed_carrier_comments(&mut graph, map_id, doc.root(), source);

    Some(PipelineSeed {
        graph,
        doc_id,
        map_id,
        top_mapping,
        anchors,
    })
}

/// Output of [`open_pipeline`] — the in-progress graph state that
/// a platform's dispatcher iterates over.
pub struct PipelineSeed<'doc> {
    pub graph: TypedGraph,
    pub doc_id: GhostId,
    pub map_id: GhostId,
    pub top_mapping: &'doc Node,
    pub anchors: AnchorTable<'doc>,
}

/// Iterate top-level entries with a closure. The closure is what
/// encodes the platform-specific "what is a job" logic.
pub fn for_each_top_entry<F>(seed: &PipelineSeed<'_>, mut f: F)
where
    F: FnMut(&Node, &str, &Node),
{
    for entry in &seed.top_mapping.children {
        if let NodeKind::MappingEntry { key_text } = &entry.kind {
            if entry.children.len() < 2 {
                continue;
            }
            f(entry, key_text, &entry.children[1]);
        }
    }
}

/// Convenience wrapper: open the pipeline, drive the closure over
/// each top-level entry, return the finished SeededGraph. For
/// platforms whose dispatch is purely per-entry. Platforms with
/// cross-entry coupling (e.g. needing the value_id of `jobs:`
/// after seeding it) should use the lower-level
/// [`open_pipeline`] / [`for_each_top_entry`] / finish manually.
pub fn seed_top_level<F>(
    doc: &Document,
    source_file: &str,
    classify: Classify<'_>,
    dispatch: F,
) -> SeededGraph
where
    F: FnMut(&mut TypedGraph, GhostId, &Node, &str, &Node, &str, &AnchorTable<'_>, Classify<'_>),
{
    seed_top_level_with_list_fields(doc, source_file, classify, &[], dispatch)
}

/// CST-level canonicalisation of `X | list<X>` construct fields: a single
/// mapping value of a list-canonical key is YAML sugar for a one-element
/// list, so wrap it in a synthetic `Sequence(SequenceItem(mapping))`. After
/// this pass the field ALWAYS presents as a sequence, so exactly ONE bijective
/// rule (seq_mapping_nodes) governs both directions — the ambiguous single
/// mapping_node shape (which collapsed N-item collections on reverse) is no
/// longer needed. The hub is identical either way (a collection); only the
/// CST surface is normalised, so NO IR data is invented. Scalars are left
/// untouched (their seq_attr/seq_scalar paths already handle single values).
/// Public entry: return a Document whose `X|list<X>` construct-field values
/// are canonicalised (single mapping → one-item sequence). Every platform
/// seeder calls this FIRST so the rest of seeding (whatever its structure)
/// sees the canonical list form — one bijective seq rule both directions.
/// No-op when `list_fields` is empty.
#[must_use]
pub fn canonicalize_document(doc: &Document, list_fields: &[&str]) -> Document {
    if list_fields.is_empty() {
        // Cheap clone-free path is impossible (Document owns its tree), but an
        // empty list means no wrapping — still must return an owned Document.
        return Document::from_parts(doc.source().to_string(), doc.root().clone());
    }
    Document::from_parts(
        doc.source().to_string(),
        canonicalize_list_fields(doc.root(), list_fields),
    )
}

fn canonicalize_list_fields(node: &Node, list_fields: &[&str]) -> Node {
    let mut out = node.clone();
    let mut new_children: Vec<Node> = node
        .children
        .iter()
        .map(|c| canonicalize_list_fields(c, list_fields))
        .collect();
    if let NodeKind::MappingEntry { key_text } = &node.kind {
        if list_fields.contains(&key_text.as_str())
            && new_children.len() >= 2
            && matches!(new_children[1].kind, NodeKind::Mapping)
        {
            let val = new_children[1].clone();
            let span = val.span;
            let item = Node {
                kind: NodeKind::SequenceItem,
                span,
                children: vec![val],
                anchor: None,
                tag: None,
            };
            new_children[1] = Node {
                kind: NodeKind::Sequence,
                span,
                children: vec![item],
                anchor: None,
                tag: None,
            };
        }
    }
    out.children = new_children;
    out
}

/// `seed_top_level` with the platform's list-canonical field keys. The doc is
/// canonicalised (single→one-item-sequence for those keys) before seeding.
pub fn seed_top_level_with_list_fields<F>(
    doc: &Document,
    source_file: &str,
    classify: Classify<'_>,
    list_fields: &[&str],
    mut dispatch: F,
) -> SeededGraph
where
    F: FnMut(&mut TypedGraph, GhostId, &Node, &str, &Node, &str, &AnchorTable<'_>, Classify<'_>),
{
    let canon_doc = canonicalize_document(doc, list_fields);
    let doc = &canon_doc;
    let Some(mut seed) = open_pipeline(doc, source_file) else {
        let source = doc.source();
        let (graph, doc_id) = make_document(source_file, source);
        return SeededGraph { graph, doc_id };
    };
    let source = doc.source();
    for entry in &seed.top_mapping.children {
        if let NodeKind::MappingEntry { key_text } = &entry.kind {
            if entry.children.len() < 2 {
                continue;
            }
            let value = &entry.children[1];
            dispatch(
                &mut seed.graph,
                seed.map_id,
                entry,
                key_text,
                value,
                source,
                &seed.anchors,
                classify,
            );
        }
    }
    SeededGraph {
        graph: seed.graph,
        doc_id: seed.doc_id,
    }
}

/// rc8 first-class re-architecture (satellites → first-class attrs):
/// lift each construct-tagged `cst:Mapping`'s SCALAR field entries onto the
/// mapping node as plain attributes (attr name = the entry key), so a field
/// rule can bind the value FIRST-CLASS onto the hub construct via the
/// construct correspondence — no `hub:attr` satellite, no `has_attr` edge.
///
/// Additive: the `cst:MappingEntry → cst:Scalar` children stay (they carry
/// per-entry provenance/comments); the lifted attribute is the value source
/// for the new first-class field rules. A "scalar field" = a construct
/// mapping entry whose value is a single `cst:Scalar`. Proven idiom:
/// `tests/first_class_attr.rs`.
pub fn lift_scalar_fields(graph: &mut TypedGraph) {
    let edges: Vec<(GhostId, GhostId, String)> = graph
        .iter_edges()
        .into_iter()
        .map(|(s, t, e)| (s, t, e.type_id.clone()))
        .collect();
    let constructs: Vec<GhostId> = graph
        .iter_nodes()
        .filter(|n| n.type_id == CST_MAPPING && n.attrs.contains_key(cst_attr::CONSTRUCT))
        .map(|n| n.id)
        .collect();
    let mut lifts: Vec<(GhostId, String, String)> = Vec::new();
    for mc in &constructs {
        for (s, entry_id, ek) in &edges {
            if s != mc || ek != CST_HAS_CHILD {
                continue;
            }
            let key = match graph.get_node(entry_id) {
                Some(n) if n.type_id == CST_MAPPING_ENTRY => match n.attrs.get(cst_attr::KEY) {
                    Some(k) => k.clone(),
                    None => continue,
                },
                _ => continue,
            };
            for (s2, sc_id, ek2) in &edges {
                if s2 != entry_id || ek2 != CST_VALUE_OF {
                    continue;
                }
                if let Some(sc) = graph.get_node(sc_id) {
                    if sc.type_id == CST_SCALAR {
                        if let Some(text) = sc.attrs.get(cst_attr::TEXT) {
                            lifts.push((*mc, key.clone(), text.clone()));
                        }
                    }
                }
            }
        }
    }
    for (mc, key, val) in lifts {
        graph.set_node_attr(&mc, &key, &val);
    }
}
